### PR TITLE
migrated to PCL and supporing UWP

### PR DESCRIPTION
**Pull request by gentledepp**
Xamarin.Auth is now PCL compatible (using bait&switch) and supports UWP web redirect authentication

### CODE REVIEW

**Comment by gentledepp** [comment]
Hi bot, I already signed that license for contributing to skiasharp.... that is annoying...

**Comment by gentledepp** [comment]
I recently got the confirmation of my newly signed license - did it work?

**Comment by moljac** [comment]
Hi 

Thanks for your PR, but there is bite-n-switch branch with UWP support. The only reason UWP was not added to nuget is that our CI servers which do th e nuget packaging and publishing were not able to build UWP projects for a while.

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch

And why is SharpSerializer needed for?

Thanks

**Comment by gentledepp** [comment]
Hi! I didn't see that.... damn...
well then forget about it.

There are actually only two features which are needed by us then:
1) Allow to enable javascript and localstorage in webauthenticators
2) allow inheriting from a WebAuthenticator in a PCL project.

Could that be done?

SharpSerializer is only for serializing and deserializing the CookieContainer, because there is no BinarySerializer on UWP unfortunately... 👎

**Comment by moljac** [comment]
Closing, because it was already implemented on portable-bait-and-switch branch.

Thanks

**Pull request closed without merging**
