### PR TITLE
Fix issue with accessing CFBoolean.TrueHandle in Xamarin.iOS 12.6 [370]

### LINKED ISSUE #370: FindAccountsForService throws on iOS
### Version

- [ ] nuget version = 1.6.0.4
- [ ] component version = 
  - VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199
  - Xamarin.iOS and Xamarin.Mac SDK   12.6.0.16 (bc9c674)
- [ ] iOS version 12.1.4

### Steps to reproduce

```
var accountStore = AccountStore.Create();
var accounts = accountStore.FindAccountsForService("someid");
```

### Expected behaviour

Not throw.

### Actual behaviour

Exception is thrown:

```
Search/Find FindAccountsForServiceAsync Object reference not set to an instance of an object
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x0007f] in <85539ee049364f3e8d64880a4a42b589>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForService (System.String serviceId) [0x00000] in <85539ee049364f3e8d64880a4a42b589>:0 
  at ShopApp.iOS.Platform.IdentityStorage.Delete () [0x00007] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\Platform\IdentityStorage.cs:117 
  at ShopApp.iOS.AppDelegate.CheckApplicationFirstLaunch (ShopApp.App application) [0x0001a] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\AppDelegate.cs:111 
  at ShopApp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00034] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\AppDelegate.cs:34 
```

Inner exception:
```
Object reference not set to an instance of an object
  at Xamarin.Auth.KeyChainAccountStore+<>c.<.cctor>b__12_2 () [0x00042] in <85539ee049364f3e8d64880a4a42b589>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x00030] in <85539ee049364f3e8d64880a4a42b589>:0 
```

I've tracked the issue down to https://github.com/xamarin/Xamarin.Auth/blob/b4fb1bb5c409e281c6bffad74ea8caba87805ea8/source/Core/Xamarin.Auth.XamarinIOS/AccountStore/KeyChainAccountStore.Aync.cs#L63-L69 where `GetField("True")` returns `null`.

> VS bug [#838824](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/838824)

### PR DESCRIPTION
**Pull request by rickykaare**
# Xamarin.Auth Pull Request

Fixes #370.

### Checklist

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Use the `CFBoolean.TrueHandle` property in latest Xamarin.iOS and fall back to the obsolete `CFBoolean.True` field available in previous version of Xamarin.iOS.

In Xamarin.iOS version prior to v12.6 the `CFBoolean` had the `True` and `False` fields:

https://github.com/xamarin/xamarin-macios/blob/monotouch-12.4.0.64/src/CoreFoundation/CFBoolean.cs#L41-L42

These where removed in Xamarin.iOS v12.6 and replaced with the `TrueHandle` and `FalseHandle` properties:

https://github.com/xamarin/xamarin-macios/blob/monotouch-12.6.0.10/src/corefoundation.cs#L35-L41

### CODE REVIEW

**Comment by moljac** [comment]
@rickykaare 

Can you provide minimal + public sample, so I can test it and verify? Please.

My time is limited (need to bump versions and release GooglePlayServices and Firebase stuff).

I will add that minimal sample to the code and test against old 1.6.0.4 nuget and new and if it is OK I will release it immediately.

Thanks

**Comment by rickykaare** [comment]
@moljac,

I was able to reproduce the error with the sample located in [samples/bugs-triaging/AccountStore](https://github.com/xamarin/Xamarin.Auth/tree/master/samples/bugs-triaging/AccountStore).

I am not sure exactly what the sample does, but the "Load" button will execute the failing `FindAccountsForService` function here:
https://github.com/xamarin/Xamarin.Auth/blob/b4fb1bb5c409e281c6bffad74ea8caba87805ea8/samples/bugs-triaging/AccountStore/AccountStoreTest/MainPage.xaml.cs#L78-L85

The call will fail in the current release of Xamarin.Auth, but will succeeds with the suggested changes in this pull-request.

**Comment by rickykaare** [comment]
In Xamarin.iOS version prior to v12.6 the `CFBoolean` had the `True` and `False` fields:

https://github.com/xamarin/xamarin-macios/blob/9c8d8e0a50e68d9abc8cd48fcd47a669e981fcc9/src/CoreFoundation/CFBoolean.cs#L41-L42

These where removed in Xamarin.iOS v12.6 and replaced with the `TrueHandle` and `FalseHandle` properties:

https://github.com/xamarin/xamarin-macios/blob/d9df1c90c5a93187141d82499c36ca82ed5dd2ba/src/corefoundation.cs#L35-L41

**Comment by moljac** [comment]
Thanks. Good catch for API change.

**Comment by sowmyajagar** [comment]
Is there an ETA on when this fix will be released?

**Pull request merged**
